test(service): add alll routes

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,38 +1,66 @@
 #!/bin/bash
-echo "Code Hook!"
+
+# Log a message function
+log_message() {
+  echo "$1"
+}
+
+log_message "Running Flutter pub get..."
+if ! output=$(flutter pub get); then
+    log_message "COMMIT REJECTED: Flutter pub get failed."
+    log_message "$output"
+    exit 1
+fi
+
 # Run Dart fix to automatically apply fixes
-echo "Running Dart fix..."
+log_message "Running Dart fix..."
 if ! output=$(dart fix --apply); then
-    echo "COMMIT REJECTED: Dart fix encountered errors:"
-    echo "$output"
+    log_message "COMMIT REJECTED: Dart fix encountered errors."
+    log_message "$output"
     exit 1
 fi
 
 # Run Dart format to ensure code is properly formatted
-echo "Running Dart format..."
+log_message "Running Dart format..."
 if ! output=$(dart format .); then
-    echo "COMMIT REJECTED: Dart format encountered errors:"
-    echo "$output"
+    log_message "COMMIT REJECTED: Dart format encountered errors."
+    log_message "$output"
     exit 1
 fi
 
 # Run Flutter analyze and check for errors
-echo "Running Flutter analyze..."
+log_message "Running Flutter analyze..."
 if ! output=$(flutter analyze); then
-    echo "COMMIT REJECTED: Flutter analyze found the following errors:"
-    echo "$output"
+    log_message "COMMIT REJECTED: Flutter analyze found the following errors."
+    log_message "$output"
     exit 1
 fi
 
 # Run Dart analyze and check for errors
-echo "Running Dart analyze..."
+log_message "Running Dart analyze..."
 if ! output=$(dart analyze); then
-    echo "COMMIT REJECTED: Dart analyze found the following errors:"
-    echo "$output"
+    log_message "COMMIT REJECTED: Dart analyze found the following errors."
+    log_message "$output"
+    exit 1
+fi
+
+# Optional: Run Flutter Doctor to check the development environment
+log_message "Running Flutter doctor..."
+if ! output=$(flutter doctor); then
+    log_message "COMMIT REJECTED: Flutter doctor found environment issues."
+    log_message "$output"
+    exit 1
+fi
+
+# Optional: Run Flutter tests to ensure that all unit tests pass
+log_message "Running Flutter tests..."
+if ! output=$(flutter test); then
+    log_message "COMMIT REJECTED: Flutter tests failed."
+    log_message "$output"
     exit 1
 fi
 
 # If we made it this far, the commit is allowed
-echo "Commit allowed!"
+log_message "Commit allowed!"
 exit 0
 
